# Generated by Django 5.1.15 on 2026-06-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialtransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("INCOME", "Income"),
                    ("EXPENSE", "Expense"),
                    ("ADJUSTMENT", "Adjustment"),
                ],
                max_length=10,
            ),
        ),
    ]
