# Generated by Django 5.1.15 on 2026-06-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MARGEN_BRUTO_BAJO', 'Margen bruto bajo'), ('GASTOS_ALTOS', 'Gastos operacionales altos'), ('AHORRO_BAJO', 'Reserva de ahorro baja'), ('CAJA_BAJA', 'Cobertura caja operacional baja'), ('CAIDA_MOM', 'Caída de ingresos consecutiva'), ('IMPUESTOS_INSUFICIENTES', 'Fondo impuestos insuficiente'), ('TICKET_CAYENDO', 'Ticket promedio cayendo'), ('OTS_PENDIENTES', 'OTs pendientes de cobro > 15 días')], max_length=30)),
                ('severidad', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Crítico')], max_length=10)),
                ('mensaje', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha', 'severidad'],
            },
        ),
    ]
