# Generated by Django 5.1.15 on 2026-06-21 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_add_alertafinanciera'),
        ('trabajos', '0002_workorder_fault_type'),
    ]

    def migrate_category_types(apps, schema_editor):
        ExpenseCategory = apps.get_model('finanzas', 'ExpenseCategory')
        ExpenseCategory.objects.filter(category_type='fixed').update(category_type='RECURRENTE')
        ExpenseCategory.objects.filter(category_type='variable').update(category_type='VARIABLE')

    operations = [
        migrations.RemoveField(
            model_name='expensecategory',
            name='monthly_budget',
        ),
        migrations.RunPython(migrate_category_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='expensecategory',
            name='category_type',
            field=models.CharField(choices=[('RECURRENTE', 'Recurrente'), ('VARIABLE', 'Variable'), ('REPUESTO', 'Repuesto')], default='VARIABLE', max_length=12),
        ),
        migrations.CreateModel(
            name='GastoPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=12)),
                ('fecha_estimada', models.DateField()),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('notas', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_pendientes', to='finanzas.expensecategory')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gasto_pendiente', to='finanzas.financialtransaction')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_pendientes', to='trabajos.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GastoRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dia_del_mes', models.PositiveSmallIntegerField(default=1, help_text='Día sugerido de pago (1-28)')),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, limit_choices_to={'category_type': 'RECURRENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_recurrentes', to='finanzas.expensecategory')),
            ],
            options={
                'ordering': ['dia_del_mes', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='gasto_recurrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finanzas.gastorecurrente'),
        ),
    ]
