# Generated by Django 5.1.15 on 2026-06-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_product_code_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='code_prefix',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
