# Generated by Django 5.1.15 on 2026-06-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_purchaseorder_purchaseorderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_equipment_component',
            field=models.BooleanField(default=False),
        ),
    ]
