# Generated by Django 5.1.15 on 2026-06-18 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_materials', to='inventario.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='catalogo.service')),
            ],
            options={
                'unique_together': {('service', 'product')},
            },
        ),
    ]
