# Generated by Django 5.1.15 on 2026-06-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_servicematerial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="metadata_calculo",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
