# Generated by Django 5.1.15 on 2026-06-18 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_service_metadata_calculo'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequiredCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('billable', models.BooleanField(default=True)),
                ('default_quantity', models.PositiveSmallIntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requirements', to='inventario.productcategory')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_categories', to='catalogo.service')),
            ],
            options={
                'ordering': ['-billable', 'label'],
                'unique_together': {('service', 'category')},
            },
        ),
    ]
