# Generated by Django 5.1.15 on 2026-06-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_servicerequiredcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
