# Generated by Django 5.1.15 on 2026-06-21 03:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_service_code_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='direct_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='service',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
