# Generated by Django 5.1.15 on 2026-06-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmpresaConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(default="VF Digital Solutions", max_length=255),
                ),
                (
                    "slogan",
                    models.CharField(
                        blank=True,
                        default="Atención directa, soluciones reales.",
                        max_length=255,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("direccion", models.TextField(blank=True)),
                ("sitio_web", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Configuración de empresa",
                "verbose_name_plural": "Configuración de empresa",
            },
        ),
    ]
