# Generated by Django 5.1.15 on 2026-06-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='fault_type',
            field=models.CharField(blank=True, choices=[('STORAGE', 'Almacenamiento / disco'), ('SCREEN', 'Pantalla'), ('BATTERY', 'Batería'), ('MOTHERBOARD', 'Placa madre'), ('KEYBOARD', 'Teclado / entrada'), ('RAM', 'Memoria RAM'), ('COOLING', 'Sistema de enfriamiento'), ('SOFTWARE', 'Software / Sistema operativo'), ('CONNECTIVITY', 'Conectividad'), ('OTHER', 'Otro')], default='', max_length=20),
        ),
    ]
