# Generated by Django 5.1.15 on 2026-06-18 17:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0003_service_metadata_calculo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialCalculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("parametros_input", models.JSONField()),
                ("resultado_calculo", models.JSONField()),
                (
                    "servicio_guardado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calculos_origen",
                        to="catalogo.service",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Cálculo",
                "verbose_name_plural": "Historial de Cálculos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="ParametrosCalculadora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sueldo_objetivo_mensual",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "costos_fijos_mensuales",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "horas_productivas_mensuales",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("50"), max_digits=6
                    ),
                ),
                (
                    "porcentaje_garantia_default",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5"), max_digits=5
                    ),
                ),
                (
                    "transporte_base_default",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5000"), max_digits=10
                    ),
                ),
                (
                    "desgaste_herramientas_default",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("500"), max_digits=10
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario_actualizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Parámetros de Calculadora",
                "verbose_name_plural": "Parámetros de Calculadora",
            },
        ),
    ]
