# Generated by Django 5.1.15 on 2026-06-17 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("source_file", models.CharField(blank=True, max_length=500)),
                ("schema_version", models.CharField(max_length=20)),
                ("raw_json", models.JSONField()),
                (
                    "ingress_source",
                    models.CharField(
                        choices=[
                            ("LOOKOUT", "Lookout"),
                            ("MOBILE_APP", "Mobile App"),
                            ("WEB", "Web"),
                        ],
                        default="LOOKOUT",
                        max_length=15,
                    ),
                ),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnoses",
                        to="equipos.equipment",
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imported_diagnoses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "diagnoses",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DetectedSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("os_name", models.CharField(blank=True, max_length=100)),
                ("os_version", models.CharField(blank=True, max_length=50)),
                ("cpu_model", models.CharField(blank=True, max_length=200)),
                (
                    "ram_total_gb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("gpu_model", models.CharField(blank=True, max_length=200)),
                (
                    "diagnosis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specification",
                        to="diagnosticos.diagnosis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManualCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field", models.CharField(max_length=100)),
                ("value", models.TextField()),
                ("corrected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "corrected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manual_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrections",
                        to="diagnosticos.diagnosis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StorageDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("INTERNAL_DISK", "Internal Disk"),
                            ("OPTICAL_DRIVE", "Optical Drive"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "disk_type",
                    models.CharField(
                        blank=True,
                        choices=[("HDD", "HDD"), ("SSD", "SSD"), ("OTHER", "Other")],
                        max_length=10,
                    ),
                ),
                (
                    "interface",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SATA", "SATA"),
                            ("NVME", "NVMe"),
                            ("IDE", "IDE"),
                            ("USB", "USB"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "capacity_gb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("raw_model", models.CharField(max_length=300)),
                (
                    "diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_devices",
                        to="diagnosticos.diagnosis",
                    ),
                ),
            ],
        ),
    ]
