# Generated by Django 5.1.15 on 2026-06-18 17:22

from django.db import migrations


GRUPOS_SISTEMA = [
    {"name": "Administradores", "color": "#d97706", "description": "Acceso completo al sistema"},
    {"name": "Técnicos",        "color": "#3b82f6", "description": "Gestión de equipos, diagnósticos y órdenes de trabajo"},
    {"name": "Vendedores",      "color": "#16a34a", "description": "Gestión de clientes, cotizaciones y ventas"},
]


def seed_grupos(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    GroupProfile = apps.get_model("usuarios", "GroupProfile")
    for datos in GRUPOS_SISTEMA:
        grupo, _ = Group.objects.get_or_create(name=datos["name"])
        GroupProfile.objects.get_or_create(
            group=grupo,
            defaults={"color": datos["color"], "description": datos["description"], "is_system": True},
        )


def remove_grupos(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for datos in GRUPOS_SISTEMA:
        Group.objects.filter(name=datos["name"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("usuarios", "0002_groupprofile"),
    ]

    operations = [
        migrations.RunPython(seed_grupos, remove_grupos),
    ]
