# Generated by Django 5.1.15 on 2026-06-17 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("NOTEBOOK", "Notebook"),
                            ("DESKTOP", "Desktop"),
                            ("AIO", "All-in-One"),
                            ("MINIPC", "Mini PC"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "desktop_subtype",
                    models.CharField(
                        blank=True,
                        choices=[("BRAND", "Brand"), ("ASSEMBLED", "Assembled")],
                        max_length=10,
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=200)),
                ("serial_number", models.CharField(blank=True, max_length=200)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "identity_key",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("is_ambiguous", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment",
                        to="clientes.client",
                    ),
                ),
            ],
        ),
    ]
