# Generated by Django 5.1.15 on 2026-06-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
