# Generated by Django 5.1.15 on 2026-06-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_equipment_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipment',
            name='cpu_brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipment',
            name='cpu_cores',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='cpu_ghz',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='equipment',
            name='gpu_brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipment',
            name='gpu_model',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='equipment',
            name='gpu_vram_gb',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='os_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='os_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipment',
            name='ram_gb',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='ram_mhz',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='ram_type',
            field=models.CharField(blank=True, choices=[('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5'), ('OTHER', 'Otro')], max_length=10),
        ),
        migrations.AddField(
            model_name='equipment',
            name='storage_brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='storage_gb',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='storage_model',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='equipment',
            name='storage_type',
            field=models.CharField(blank=True, choices=[('HDD', 'HDD'), ('SSD', 'SSD (SATA)'), ('NVME', 'NVMe'), ('OTHER', 'Otro')], max_length=10),
        ),
    ]
