# Generated by Django 5.1.15 on 2026-06-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_equipment_detailed_specs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='cpu_brand',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='cpu_cores',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='cpu_ghz',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='cpu_model',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='gpu_brand',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='gpu_model',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='gpu_vram_gb',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='os_name',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='os_version',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='ram_gb',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='ram_mhz',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='ram_type',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='storage_brand',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='storage_gb',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='storage_model',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='storage_type',
        ),
        migrations.AddField(
            model_name='equipment',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
