# Generated by Django 5.1.15 on 2026-06-17 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("PERSON", "Person"), ("COMPANY", "Company")],
                        max_length=10,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("second_last_name", models.CharField(blank=True, max_length=100)),
                (
                    "identity_key",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("phone", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("rut", models.CharField(blank=True, max_length=20)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("address", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("LOOKOUT", "Lookout"), ("MANUAL", "Manual")],
                        default="MANUAL",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="absorbed_clients",
                        to="clientes.client",
                    ),
                ),
            ],
        ),
    ]
