# Generated by Django 5.1.15 on 2026-06-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_allow_blank_name_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
